// A small library of COMPLETE worked studies — what a study-shaped pour
// actually deals now: a titled, fully written exemplar (every section of
// its template composed, not just the first seeded), the way a study
// Bible ships worked helps rather than blank outlines. Hand-authored for
// this app and independently fact-checked (WebSearch-verified authorship
// traditions and NT-warrant claims, hedged wherever real scholarship
// disputes), written fresh rather than copied from any published
// commentary — the same content discipline bibleBookDetails.js already
// holds. Each study's PRIMARY passage text was fetched verbatim from
// bible-api.com's KJV at generation time (never typed from memory) and
// carries its citation tag inline, and every inline citation was
// validated through parseCitationsDetailed before this file was written —
// the pills row, per-section grouping, layered-sense marks, and typology
// arrows all light up on these studies because they are written in the
// app's own citation grammar, not merely displayed text.
//
// Stored as structured { templateId, sections } and serialized through
// stringifyStudy at module load — never as pre-baked heading text — so a
// future change to a template's headings can't silently strand the
// library on an old grammar (the one-serializer discipline study.js's own
// detection/parsing already keeps).
import { STUDY_TEMPLATES, stringifyStudy } from "./study";

const ENTRIES = [
  {
    templateId: "inductive",
    reference: "Psalms 23:1",
    title: "My Shepherd, My Sufficiency",
    sections: {
      observation: "The LORD is my shepherd; I shall not want. (Psalms 23:1)\n\nThe psalm comes down to us under the ancient heading 'A Psalm of David', and that attribution is received here as the title's own claim. The opening verse holds exactly two clauses: a metaphor naming the LORD — the covenant name of Israel's God — as the speaker's own shepherd, and the consequence the speaker draws from it, that he will lack nothing. Observe the singular possessive: this is personal confession, not a national creed. Observe also that the second clause is unqualified; no conditions are attached to it. Everything that follows in the poem simply unfolds this one image — pastures, waters, a restored soul, right paths (Psalms 23:2-3) — before the scene shifts to a spread table and an overflowing cup.",
      interpretation: "Shepherding was David's own first trade; he describes to Saul his defense of the flock against lion and bear (1 Samuel 17:34-35). In the ancient Near East, shepherd was also stock royal language, and Israel's scriptures apply it to God himself, the Shepherd of Israel who leads Joseph like a flock (Psalms 80:1). The confession therefore sets the singer among the covenant people while making the relation intimately personal. To lack nothing does not promise luxury or exemption; the psalm itself passes through a death-shadowed valley a few verses on. It promises that under this shepherd's competence and character, nothing truly needed will finally be missing. The ground of the confidence is not the sheep's circumstances but the shepherd's identity.",
      application: "A confession like this one is tested by anxiety. Where worry insists that our welfare rests on our own management, the verse relocates it in a person whose care does not fail. The honest application is trust practiced in specifics: naming the present want and asking whether the shepherd is unaware of it or unable to meet it. The New Testament invites Christian readers to say the confession with a face in view: Jesus calls himself the good shepherd who lays down his life for the sheep (John 10:11), and Peter tells returning strays they have come back to the Shepherd of their souls (1 Peter 2:25). Contentment grows exactly where that identification is believed.",
    },
  },
  {
    templateId: "inductive",
    reference: "James 1:22-25",
    title: "The Mirror and the Doer",
    sections: {
      observation: "But be ye doers of the word, and not hearers only, deceiving your own selves. For if any be a hearer of the word, and not a doer, he is like unto a man beholding his natural face in a glass: For he beholdeth himself, and goeth his way, and straightway forgetteth what manner of man he was. But whoso looketh into the perfect law of liberty, and continueth therein, he being not a forgetful hearer, but a doer of the work, this man shall be blessed in his deed. (James 1:22-25)\n\nThe paragraph moves as command, warning, picture, and promise. The command: act on what is heard. The warning: listening without doing is a way of deceiving oneself. The picture: a man glances at his own face in a mirror, walks away, and straightway forgets what he saw. Against him James sets a second figure, one who bends close over the law he calls perfect and freeing, stays with it, and acts — and the acting, not the hearing, carries the blessing. Note who does what: both men look, but only one continues. The immediate context has just urged readers to receive the implanted word with meekness (James 1:21), so this paragraph shows what genuine reception looks like afterward.",
      interpretation: "The letter is traditionally attributed to James the brother of the Lord, and whoever wrote it, it reads like Christian wisdom literature: short units, vivid similes, the moral texture of Proverbs. Its nearest kin is the teaching of Jesus himself; hearing-versus-doing is precisely the contrast that closes the Sermon on the Mount, where the two builders differ only in whether they act on the words (Matthew 7:24-27). First-century mirrors were polished metal, suited to a glance rather than a study; the point is not poor reflection but brief attention. The law of liberty returns later in the letter as the standard of coming judgment (James 2:12): for James, the word that frees is also the word that obligates.",
      application: "The test this passage sets is uncomfortably measurable: what changed after the last time we heard or read the word? Jesus made the same connection between doing and blessedness — 'happy are ye if ye do them' (John 13:17) — and pressed the question of calling him Lord while not doing what he says (Luke 6:46). A workable discipline follows the mirror image: linger rather than glance, and leave each reading with one concrete act named — a wrong to put right, a tongue to bridle, a need to meet. James's own letter goes on to define pure religion in just such terms. Blessing, on his account, is found in the deed, not in the impression the hearing left.",
    },
  },
  {
    templateId: "inductive",
    reference: "Luke 15:20",
    title: "When the Father Ran",
    sections: {
      observation: "And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him. (Luke 15:20)\n\nThe verse sits inside a scene Luke frames carefully: tax collectors and sinners drawing near to hear Jesus, while Pharisees and scribes murmur that he receives them (Luke 15:1-2). Three parables of lost things answer the murmur, and this verse is the hinge of the third. Count the verbs. The son receives two — rising and coming home. The father receives five: seeing at a distance, feeling compassion, running, embracing, kissing. The embrace arrives before the rehearsed confession is even spoken (Luke 15:21). Distance, sight, feeling, motion, touch: the sentence itself sprints. Whatever else the parable teaches, its grammar places the initiative squarely with the father.",
      interpretation: "In context the parable is Jesus's defense of his own table: the murmuring elders correspond to the elder brother who will not come in (Luke 15:28-30), and the father's welcome pictures God's welcome of repenting sinners. Luke's compassion verb is the one he uses of Jesus at the gate of Nain (Luke 7:13); the evangelist lets the father's feeling and Jesus's feeling share a vocabulary. Commentators often add that for a village patriarch to run was startlingly undignified, though the text's own stress falls simply on his initiative. Hearers formed by Israel's scriptures would recognize the portrait, for God had named himself merciful and gracious, slow to anger (Exodus 34:6). Jesus is not inventing a new God; he is narrating the confessed one.",
      application: "The parable searches both sons in us. To the returning one it says: the prepared speech about becoming a hired servant is interrupted by a kiss; repentance is met with embrace, not probation, and heaven's joy over one sinner repenting (Luke 15:7) rebukes our fear of coming home. To the elder-brother reflex it says: watch what murmurs in you when grace runs past your faithfulness toward someone undeserving. Churches inherit either the father's posture or the Pharisees'; the chapter offers no third stance. Practically, this looks like taking the first steps toward people who are still a long way off — before apologies are polished, before terms are negotiated — because that is how the father in the story loved.",
      sensusPlenior: "Read within the whole canon, the father's run carries a sense fuller than the parable's occasion. God had proclaimed his name to Moses as merciful and gracious, longsuffering, abundant in goodness (Exodus 34:6), and the Psalter had already made the image paternal — a father pitying his children (Psalms 103:13). The parable enacts that self-revelation in narrative form. The canon then presses further than the story itself goes: the actual bringing-near of those far off is accomplished in Christ, in whose blood the distant are 'made nigh' (Ephesians 2:13). This is argued from converging texts, not free association — Luke's compassion vocabulary, the Sinai name the parable presupposes, and Paul's far-and-near pattern. Canonically read, the father's embrace has a cost the parable leaves unspoken.",
    },
  },
  {
    templateId: "quadriga",
    reference: "Genesis 22:8",
    title: "The Lamb God Provides",
    sections: {
      literal: "And Abraham said, My son, God will provide himself a lamb for a burnt offering: so they went both of them together. (Genesis 22:8)\n\nAbraham speaks these words to Isaac on the road up Moriah, where God has commanded him to offer his only son as a burnt offering (Genesis 22:1-2). Genesis is traditionally attributed to Moses, and the account was preserved for Israel as the defining trial of their forefather's faith. Read literally, the answer expresses trust under extremity: God himself will see to the offering. The narrative honors that trust when a ram caught in a thicket dies in Isaac's place (Genesis 22:13), and Abraham names the site for what happened there, for the LORD did provide (Genesis 22:14). The literal sense is a father's tested faith and a God who supplies the sacrifice he demands.",
      allegorical: "The church has long heard in Abraham's answer more than the patriarch could see, and the New Testament supplies the warrant. When John the Baptist points to Jesus as \"the Lamb of God\" (Genesis 22:8 -> John 1:29), he gives the church its lens for Moriah: the ram met that day's need, but the lamb of Abraham's sentence was still to come, a lamb without blemish foreordained before the foundation of the world (1 Peter 1:19-20). Allegorically the scene stages the gospel in advance — the father, the beloved son, the wood carried up the hill (Genesis 22:6), and the substitute God himself supplies.",
      tropological: "Morally, the passage forms the obedience of faith. Abraham rose early in the morning to obey the hardest command he had ever received (Genesis 22:3), and James points to this very scene to argue that faith is made perfect by works (James 2:21-22). The tropological lesson is not that God asks parents for their children; the ram forecloses that reading. It is that trust precedes sight: the believer obeys before the provision appears, confident that the God who commands is also the God who supplies every need (Philippians 4:19).",
      anagogical: "Abraham's name for the mountain carries a forward edge, for the saying persisted that \"in the mount of the LORD it shall be seen\" (Genesis 22:14). What Moriah glimpsed, the end of Scripture consummates: the city needs no sun, for the Lamb is its light (Revelation 21:23), and the blessed are called to the marriage supper of the Lamb (Revelation 19:9). Anagogically, the provision of God ends not in a ram caught in a thicket but in a feast, where the Lamb once provided as sacrifice presides as host, and provision and presence are finally one.",
      sensusPlenior: "Beyond what the human author could have framed lies the pattern the whole canon discloses: a father offering his only son and receiving him back. Hebrews makes this the text's own fuller sense, saying that Abraham accounted God able to raise Isaac from the dead, and received him \"in a figure\" (Hebrews 11:17-19). Paul seems to echo the oath sworn at Moriah — because Abraham withheld not his son (Genesis 22:16) — when he writes that God \"spared not his own Son\" (Romans 8:32). The divinely intended sense runs deeper than the human hope: what Abraham's mouth confessed at the literal level, the Father enacted at Calvary, providing himself the Lamb.",
    },
  },
  {
    templateId: "quadriga",
    reference: "Exodus 12:13",
    title: "The Blood for a Token",
    sections: {
      literal: "And the blood shall be to you for a token upon the houses where ye are: and when I see the blood, I will pass over you, and the plague shall not be upon you to destroy you, when I smite the land of Egypt. (Exodus 12:13)\n\nThe instruction comes on the eve of the tenth plague, as the LORD prepares to smite the firstborn of Egypt and commands each Israelite household to slay an unblemished lamb and strike its blood on the doorposts and lintel (Exodus 12:3-7). Exodus is traditionally attributed to Moses. Literally, the blood is a sign marking the houses of those who took God at his word: when the destroyer passes through, the LORD will not suffer him to enter a marked house (Exodus 12:23). The night was then fixed in Israel's calendar as a memorial to be kept throughout their generations (Exodus 12:14). The sign saves not by magic but by marking obedient trust.",
      allegorical: "Paul supplies the New Testament's own warrant for reading the Passover christologically, telling the Corinthians plainly that Christ is \"our passover\" sacrificed for us (Exodus 12:13 -> 1 Corinthians 5:7). John's Gospel presses the identification: Jesus dies at Passover season, and the rule that no bone of the lamb be broken (Exodus 12:46) is fulfilled at the cross (John 19:36). Peter completes the figure, describing redemption by the precious blood of Christ as of a lamb without blemish and without spot (1 Peter 1:18-19). Allegorically, the blood on the doorposts is the blood of Christ, and the judgment that swept Egypt passes over every house sheltered beneath it.",
      tropological: "Paul draws the moral sense in the same breath as the doctrinal: because Christ our passover is sacrificed, the church must \"purge out the old leaven\" (1 Corinthians 5:7). The first Passover household did not merely apply blood; it cleared the house of leaven (Exodus 12:15) and ate girded for departure (Exodus 12:11). So the believer keeps the feast with the unleavened bread of sincerity and truth rather than the leaven of malice (1 Corinthians 5:8). Tropologically, this verse describes a household swept clean — a people whose daily conduct answers to the blood that already marks their door.",
      anagogical: "The first Passover night opened into exodus, and that shape recurs at the story's end. John sees the redeemed standing by a sea of glass, singing the song of Moses the servant of God and the song of the Lamb (Revelation 15:3), and heaven's worship centers on the Lamb who was slain and whose blood purchased a people from every nation (Revelation 5:9). Anagogically, the token on the doorposts anticipates a final passing over of judgment: a deliverance no Pharaoh can revoke, when the marked and sheltered households of God come out at last into liberty.",
    },
  },
  {
    templateId: "quadriga",
    reference: "Jonah 1:17",
    title: "The Sign of Jonah",
    sections: {
      literal: "Now the LORD had prepared a great fish to swallow up Jonah. And Jonah was in the belly of the fish three days and three nights. (Jonah 1:17)\n\nThe verse closes the storm narrative: Jonah, fleeing toward Tarshish from the presence of the LORD (Jonah 1:3), has been thrown into the sea at his own word, and the LORD prepares a great fish to swallow him. The prophet is named elsewhere as Jonah the son of Amittai, who prophesied in the days of Jeroboam II (2 Kings 14:25), though the book's date and genre remain genuinely debated among scholars. Literally, the fish is rescue rather than punishment: three days and three nights in its belly preserve a drowning man, and it is from that belly that the prophet finally prays (Jonah 2:1).",
      allegorical: "Here the warrant for a spiritual sense is as strong as Scripture affords, for it is Jesus's own. Asked for a sign, he offers only the sign of the prophet Jonah: as the prophet lay three days and three nights in the fish, so the Son of man would lie in the heart of the earth (Jonah 1:17 -> Matthew 12:40). The Lord himself reads his burial through this verse, and Luke's parallel makes Jonah himself a sign to his generation (Luke 11:30). The church adds nothing when it sees the tomb in the fish's belly; it simply follows its Master's exegesis.",
      tropological: "The moral edge of the sign cuts toward its hearers: the men of Nineveh repented at Jonah's preaching, and one greater than Jonah stands before them (Matthew 12:41). If pagan Nineveh turned at a reluctant prophet's word, no excuse remains for those who hear the Son himself. The verse also searches the believer through Jonah's own arc, for it is at the bottom of his flight, inside the fish, that he at last cries out and is heard (Jonah 2:1-2). Tropologically, no self-made ruin lies too deep for prayer, and no cry from the depths goes unanswered.",
      anagogical: "Because Jesus made the fish's belly a figure of the heart of the earth, the three days carry the church's final hope: an entombment measured, bounded, and ended (Jonah 1:17). Jonah's psalm closes with the confession that salvation belongs to the LORD (Jonah 2:9), and he is returned alive to dry land as Christ rose the third day according to the scriptures (1 Corinthians 15:4). Anagogically, the deep does not keep what God has claimed. The risen Christ is the firstfruits of them that slept (1 Corinthians 15:20), and the sign of Jonah becomes the sign over every grave God intends to open.",
    },
  },
  {
    templateId: "lectio",
    reference: "Psalms 46:10",
    title: "Stillness in the Uproar",
    sections: {
      lectio: "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth. (Psalms 46:10)\n\nSlow down over the words themselves before rushing to comfort. The command to be still renders the Hebrew harpu, from a root meaning to let drop, to slacken the grip — nearer to 'cease striving,' even 'lay down your arms,' than to a whispered hush. And the setting is anything but hushed: this psalm has already watched mountains carried into the midst of the sea, heard the heathen rage, and seen God break the bow and burn the chariot (Psalms 46:2-3; Psalms 46:6; Psalms 46:9). The command falls first on the raging nations: stop your striving, and know who is God, exalted whether or not you consent. Stillness here is not a mood to be curated; it is a contest surrendered.",
      meditatio: "The canon keeps issuing this command at the edge of catastrophe. At the sea, with Pharaoh's chariots closing, Israel is told to stand still and see the salvation of the LORD, for the LORD himself will fight (Exodus 14:13-14). On Galilee, the Lord of the storm speaks one word to wind and water and they obey him (Mark 4:39). And notice the refrain this psalm sets on either side of its chaos: the LORD of hosts — of armies — is with us, the God of Jacob our refuge (Psalms 46:7). Stillness is commanded not because the threat is small but because the warrior is God. The same voice that makes wars cease can end the war in you.",
      oratio: "Lord of hosts, I loosen my grip. The things I have clenched — outcomes I cannot command, arguments I cannot win, futures I cannot secure — I let them drop from my hands into yours. You told your cornered people to stand still and see your salvation (Exodus 14:13-14); tell me again, for I am cornered by smaller armies and I strive as though rescue were my own work. Be exalted where I have exalted my anxiety. Be known where I have only calculated. I do not ask you to remove the uproar today; I ask you to be God in the middle of it, and to let me stop fighting long enough to see. Amen.",
      contemplatio: "Now let even the prayer fall silent. Do not manufacture serenity; simply stop striving for one unhurried stretch and let the fact stand on its own: he is God, and you are not, and that is good news. The river that gladdens the city of God keeps running (Psalms 46:4) whether or not your hands are busy. Sit beside it. When the mind picks its weapons back up, do not scold it; just open the hands again. Knowing, in this verse, is not mastering information but resting under a sovereignty you were never asked to carry.",
    },
  },
  {
    templateId: "lectio",
    reference: "John 15:4",
    title: "Abiding in the Vine",
    sections: {
      lectio: "Abide in me, and I in you. As the branch cannot bear fruit of itself, except it abide in the vine; no more can ye, except ye abide in me. (John 15:4)\n\nLet the key word settle before anything else: abide — the Greek meno, to remain, to stay, to make one's home. The Lord repeats it like a heartbeat through this whole discourse (John 15:5-10), as if he knew our danger is rarely dramatic apostasy and usually quiet drift. Notice that the command assumes a union already given: the branch is not told to graft itself in, only to remain where grace has placed it. Notice the mutuality the verse promises — his remaining in you answering yours in him. And notice the stark honesty about the alternative: not smaller fruit but none, for a branch that lives on its own supply is only pretending to be alive.",
      meditatio: "The vine is Israel's oldest self-portrait. God brought a vine out of Egypt, cast out the heathen, and planted it (Psalms 80:8). The beloved planted a vineyard on a fruitful hill, looked for grapes, and gathered wild ones (Isaiah 5:1-7). A noble vine turned degenerate in his hand (Jeremiah 2:21). Against that long disappointment, this discourse opens with a claim that would startle any reader of the prophets: the true vine, at last, is a person (John 15:1). So when Jesus says abide, he is not decorating a sermon with greenery; he is standing inside Israel's whole story and offering to carry you into it, where the fruit God has always looked for can finally grow.",
      oratio: "Lord Jesus, true vine, I have tried to bear fruit on my own sap and produced mostly leaves. Keep me where you have planted me. When I measure my usefulness by activity, remind me that a branch's one task is attachment. Prune what you must (John 15:2) — I flinch as I pray it, but better the husbandman's knife than a wild and barren spread. Let your words abide in me until my asking bends toward your willing (John 15:7). I do not request a spectacular life; I ask to remain. And since my grip is weaker than yours, let the holding, like the sap, come from your side. Amen.",
      contemplatio: "Rest now inside the image rather than analyzing it. A branch does not strain to abide; it simply does not leave. Sap rises without the branch's supervision. For a few unhurried minutes, be that: attached, supplied, unspectacular. Fruit, when it comes, will be almost none of your business — the branch is the last to see its own grapes. Let the promise of his abiding in you be enough for today. You are not the vine, not the husbandman, not the harvest schedule. You are held wood in living wood, and the life moving through you is not your own.",
      sensusPlenior: "Read whole, the canon discloses more here than a farming metaphor. Israel was the vine God planted and the vineyard that failed its owner, and John's word 'true' supplies the warrant for hearing Jesus claim that identity: he is the vine Israel was meant to be, recapitulating her story and bearing what she would not (Psalms 80:8 -> John 15:1; Isaiah 5:7 -> John 15:1). The vine psalm itself reaches forward, praying for the man of God's right hand, the son of man made strong for himself (Psalms 80:17) — a plea this discourse answers in person. The fuller sense, then: to abide in Christ is to be gathered into the true Israel, yielding at last the grapes the owner came seeking (Isaiah 5:4).",
    },
  },
  {
    templateId: "lectio",
    reference: "Psalms 131:2",
    title: "The Weaned Soul",
    sections: {
      lectio: "Surely I have behaved and quieted myself, as a child that is weaned of his mother: my soul is even as a weaned child. (Psalms 131:2)\n\nThe superscription names this a Song of degrees and attributes it to David — a pilgrim song for the climb toward Jerusalem, and among the shortest of the climbs at three verses. The line before has just renounced haughty eyes and matters too high (Psalms 131:1), and now comes the psalm's single image. Mark the verbs: the psalmist has behaved and quieted his own soul — behaved being older English for deliberately composed — so the calm was worked for, not stumbled into, and weaning is not gentle while it happens. Mark also which child he chooses: weaned, not nursing. A nursing infant is at its mother for what she supplies; a weaned child leans against the same breast wanting nothing but her. Desire has moved from the gift to the giver.",
      meditatio: "This smallness runs through the scriptures like a secret. The Lord says that unless we be converted and become as little children we shall not enter the kingdom, and that the humbled child is the kingdom's greatest (Matthew 18:3-4); he offers rest precisely because he is meek and lowly in heart (Matthew 11:29). The ascent song sung one step before this one waits for the LORD more than watchmen wait for the morning (Psalms 130:5-6). And the apostles hand the same posture on: humble yourselves under the mighty hand of God, casting every care on him who cares for you (1 Peter 5:6-7). The climb to God's house turns out, strangely, to be a climb downward.",
      oratio: "Father, wean me. I still cry for what you give more than for who you are, and my soul is loud with wanting. Do in me the slow work a mother does: withhold what I have outgrown until I stop grasping, and let me find that you were the comfort underneath every comfort all along. I lay down, today, the great matters I have used to feel large. Quiet me — not the quiet of finally getting my way, but the quiet of a child who has stopped negotiating and simply leans. And when the weaning aches, keep me against you, not away from you. Amen.",
      contemplatio: "Stay in the posture the psalm ends with: hope in the LORD, from now and for ever (Psalms 131:3). Do not reach for insight; a weaned child does not analyze its mother. Let ambition, even spiritual ambition, sit outside the door for a while. You are small, and it is safe to be small here. Breathe at the pace of someone with nowhere left to climb. If a thought insists it is urgent, let it wait as you would teach a child to wait. Presence is the whole meal now. This, too, is ascent — the last few steps are always taken leaning.",
    },
  },
  {
    templateId: "doctrineUse",
    reference: "Romans 5:1",
    title: "The Peace of the Justified",
    sections: {
      text: "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ: (Romans 5:1)\n\nThe apostle's opening word gathers up the whole argument that precedes it. Abraham believed God, and it was counted to him for righteousness (Genesis 15:6; Romans 4:3); and what was written of him was written for all who share his faith. Being justified, then, is a verdict already passed, not a process still pending, grounded in Christ delivered for our offences and raised again for our justification (Romans 4:25). Many ancient copies, among them some of the earliest, read the verb as an exhortation, let us have peace, and a single Greek vowel divides the manuscripts; but the drift of the argument favors the settled declaration the translators give us: peace possessed, not peace pursued.",
      doctrine: "Doctrine: God freely justifies the ungodly through faith alone, and the first fruit of this verdict is peace with God through our Lord Jesus Christ. Justification is not the making of a man righteous within but the declaring of him righteous in God's court; faith contributes no merit, being only the empty hand that receives what grace holds out to him that worketh not but believeth (Romans 4:5). The peace that follows is objective before it is felt: the war is ended, the sentence lifted, and God is no longer an adversary to the believing sinner. Where the court has spoken, the conscience may safely rest.",
      use: "First, for conviction: whoever labors to make his peace before believing inverts the order of the text; works follow the verdict and never procure it. Second, for comfort: this peace stands in God's court, not in the believer's frame; the doubting saint's justification is no less firm than the rejoicing saint's, for no condemnation remains to those in Christ Jesus (Romans 8:1). Let the troubled conscience reason from the verdict to the feeling, never from the feeling to the verdict. Third, for practice: those at peace with God have access into a standing grace, and may glory even in tribulations, knowing the chain that runs from suffering through patience to hope (Romans 5:2-4).",
    },
  },
  {
    templateId: "doctrineUse",
    reference: "Ephesians 2:8-9",
    title: "The Gift That Silences Boasting",
    sections: {
      text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast. (Ephesians 2:8-9)\n\nThese words stand at the summit of a resurrection narrative. Paul has described men dead in trespasses and sins (Ephesians 2:1), then quickened, raised, and seated with Christ, God acting upon the dead out of rich mercy and great love (Ephesians 2:4-6). Salvation is therefore spoken of as a thing done, not a thing attempted. One clause has a debated reach: the pronoun rendered that is neuter in the Greek while faith is a feminine noun, so many interpreters take the gift to be the whole saving work, grace, faith, and all, rather than faith narrowly; on either reading nothing in the sentence originates with man. The closing clause bars boasting before it can begin.",
      doctrine: "Doctrine: Salvation, from its first motion to its final glory, is the free gift of God, received through faith and in no part earned by works. Grace is not God's response to human effort but its replacement; he saves according to his mercy, not by righteous works of ours (Titus 3:5). Faith itself, as the instrument of receiving, confers no merit on the receiver, for a beggar's hand does not enrich the alms. The design of the arrangement is doxological: boasting is excluded by the law of faith, so that all glorying is glorying in the Lord (Romans 3:27; 1 Corinthians 1:31). What costs the sinner nothing cost the Giver everything.",
      use: "First, for conviction: the religion of the natural heart is wages, and this text ends it; whoever brings his praying, his morality, or his tears as part-payment must be stripped down to the empty hand. Second, for comfort: what rests on grace cannot be forfeited by the weakness of the hand that holds it; a trembling faith receives the same Christ as a strong one, for the security lies in the Giver, not the grip. Third, for practice: works excluded from the root are commanded in the fruit; we are his workmanship, created unto good works prepared beforehand for our walking (Ephesians 2:10). Gratitude, not bargaining, is henceforth the spring of all obedience.",
    },
  },
  {
    templateId: "doctrineUse",
    reference: "Isaiah 53:5",
    title: "Healed by His Stripes",
    sections: {
      text: "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed. (Isaiah 53:5)\n\nThe verse lies at the heart of the fourth Servant song, which opens with the Servant's exaltation (Isaiah 52:13) and moves through humiliation to triumph. The speakers are a confessing we, astonished to discover that the sufferings they once read as God's judgment upon the sufferer were in fact their own punishment borne by another. The Hebrew verbs are violent, pierced through and crushed; the blows that purchased our peace fell on him, the wounds were his, the healing ours. Who the Servant is has long been debated, Jewish interpretation from antiquity onward sometimes reading Israel personified; yet the song describes one who suffers for the we, guiltless in deed and word, which strains the corporate reading (Isaiah 53:9).",
      doctrine: "Doctrine: God laid upon his righteous Servant the punishment his people deserved, and by that substitution they have peace and healing (Isaiah 53:5). This is exchange, and not example merely: our transgressions the cause, his wounds the cost, our peace the purchase. The Lord himself made the transfer, laying on him the iniquity of us all, and it pleased the Lord to bruise him (Isaiah 53:6, Isaiah 53:10); the suffering was no accident of history but the counsel of God prospering in the Servant's hand. Justice is satisfied and the sinner spared in one and the same act; mercy does not waive the debt but moves another to pay it.",
      use: "First, for conviction: the text names the wounding party; it was for our transgressions, and every easy thought of sin must die before this spectacle. Second, for comfort: the chastisement of our peace was laid on him, so no chastisement of wrath remains for those he heals; their afflictions are henceforth fatherly, never penal. Third, for practice: Peter draws both duties from this very verse, that being dead to sins we should live unto righteousness, and that we should bear wrongs patiently after the pattern of him who suffered without threatening (1 Peter 2:21-24). The healed life is not given back to us for ourselves; it spends itself as the Healer did.",
      sensusPlenior: "The fuller sense of this verse is not a later imposition but the New Testament's own claim. When the Ethiopian asked of whom the prophet spoke, Philip began at the same scripture and preached Jesus to him (Acts 8:32-35). Peter quotes the verse directly, \"by whose stripes ye were healed,\" and locates those stripes at the cross, where Christ bore our sins in his own body on the tree (1 Peter 2:24; Isaiah 53:5). The Servant led as a lamb to the slaughter is, on this apostolic warrant, the Lamb whom John announces as bearing away the world's sin (Isaiah 53:7 -> John 1:29). What Isaiah's first hearers met as the Servant's mystery, the whole canon discloses as the crucified and risen Christ.",
    },
  },
  {
    templateId: "exegetical",
    reference: "Genesis 1:1",
    title: "The Unopposed Beginning",
    sections: {
      passage: "In the beginning God created the heaven and the earth. (Genesis 1:1)\n\nThe Bible's first sentence is less a report than a claim staked over everything that follows. Before any human actor appears, God acts, and the verse names him as the subject of the whole drama. Read as the superscription of the seven-day account it introduces, it asserts that the heavens and the earth owe their existence to God alone. The writer offers no argument for God's existence and no account of God's origin; both silences are deliberate. The letter to the Hebrews later takes exactly this verse's claim as the ground of faith's understanding of the world, framed by the word of God so that the visible arose from what does not appear (Hebrews 11:3).",
      context: "Jewish and Christian tradition attributes the Pentateuch to Moses, and later Scripture speaks of it as the book of Moses; modern critical scholarship, however, has long debated its composition. The documentary hypothesis assigns Genesis 1 to a Priestly source, which many critics date to the exilic or post-exilic period, while other scholars contest both the source division and the late dating; the question remains genuinely open. Literarily, the chapter stands in quiet polemic against the cosmogonies of Israel's neighbors, in which the world emerges from divine combat or the birth of gods. Genesis knows no rival deities, no struggle, no theogony — only the unopposed speech and act of the one God.",
      observations: "The opening word, bereshit, 'in the beginning,' gives the Hebrew Bible its own name for this book. The verb rendered 'created' (bara) takes God alone as its subject throughout the Old Testament: humans make, form, and build, but only God creates in this sense. Grammarians debate whether the verse is an independent sentence or a dependent clause introducing verse 2 — 'when God began to create' — a question with real translational stakes, though the traditional independent reading remains well defended. 'The heaven and the earth' functions as a merism, naming the two extremes in order to embrace everything between them, the same totality the psalmist credits to the word and breath of the LORD (Psalms 33:6).",
      theology: "Canonically, this verse becomes the seed of a Christological confession. John opens his Gospel by rewriting it, locating the Word in the beginning with God, so that nothing made was made without him (John 1:1-3). Paul presses further: all things were created by the Son, and for him (Colossians 1:16). The doctrine of creation from nothing is not stated here in so many words, but the canon moves steadily in that direction, as when Paul describes God as calling into being the things that are not (Romans 4:17). In the Bible's full witness, creation is not merely the first event; it is the first act of the same God whose purposes run through Christ to the end.",
      significance: "A reader who takes this verse seriously can no longer treat the world as accident, as the battlefield of rival gods, or as raw material without meaning. Everything encountered — matter, time, sky, self — is creature, and therefore neither divine nor worthless. That double negation grounds both worship and sanity: the Creator alone is to be adored, while the made world may be studied, tended, and enjoyed without being feared. It also grounds hope, for the God who began all things without assistance is competent to renew them. To confess the Bible's first sentence is to accept a place in someone else's story, and Scripture's consistent testimony is that creatures flourish exactly there.",
    },
  },
  {
    templateId: "exegetical",
    reference: "John 1:1-5",
    title: "The Word Before the World",
    sections: {
      passage: "In the beginning was the Word, and the Word was with God, and the Word was God. The same was in the beginning with God. All things were made by him; and without him was not any thing made that was made. In him was life; and the life was the light of men. And the light shineth in darkness; and the darkness comprehended it not. (John 1:1-5)\n\nJohn opens his Gospel not at Bethlehem but before creation itself. The first clause deliberately reproduces the opening of Scripture (Genesis 1:1), so that the reader hears Genesis behind every phrase: beginning, God, light, darkness, life. But where Genesis begins with God speaking, John begins with the Word who simply was — already present, already with God, already God. Verses 3 through 5 then rerun the creation story with the Word as its agent, and close on a note of conflict absent from Genesis 1: the light shines in a darkness that has not mastered it. The prologue thus announces its theme before naming its subject; Jesus does not appear by name until later in the chapter.",
      context: "Tradition attested from the second century names the author as John the apostle, the beloved disciple; much modern scholarship regards the question as more complicated, positing a Johannine community or school behind the Gospel, and the debate is unresolved. The book is commonly dated toward the end of the first century. Some scholars propose that the prologue adapts an earlier hymn to the Word, a suggestion that remains a proposal rather than a consensus. The background of the term logos is likewise contested: Greek philosophy used it for the world's rational principle, while Jewish tradition personified God's wisdom and celebrated the word by which the heavens were made. John's usage seems calculated to be heard in both worlds while being controlled by neither.",
      observations: "The key term is logos, 'Word,' sounded three times in the first verse. The prologue advances by staircase parallelism, each line picking up a word from the line before: Word and God, him and life, life and light. A crucial contrast runs between the verb of being used of the Word — he was, continuously — and the verb of becoming used of created things, which were made. The Word stands on the Creator's side of that line, which is the point of verse 3's insistence that not one made thing was made without him. In verse 5 the verb rendered 'comprehended' is ambiguous, meaning either to grasp mentally or to overtake and overcome; John may intend both: the darkness has neither understood the light nor extinguished it.",
      theology: "Read canonically, the prologue makes creation a Christological doctrine. The Word who was in the beginning (Genesis 1:1) is the one through whom all things were made, a claim the wider New Testament shares when it says all things were created by the Son and hold together in him (Colossians 1:16). The light-in-darkness motif likewise carries forward: Paul explicitly reads the first creative command, 'Let there be light,' as the pattern of the illumination God now works in the heart through the gospel of Christ (Genesis 1:3 -> 2 Corinthians 4:6), modeling new creation on old. The prologue also guards a distinction the later church would labor to state precisely: the Word is God, yet with God — full identity of nature without collapse of persons.",
      significance: "If the Word was in the beginning, then Jesus of Nazareth is not a late footnote to the world's story but its author entering the plot. Everything this Gospel will narrate — signs, discourses, cross, empty tomb — is the work of the one through whom the readers themselves were made. The prologue therefore forbids two comfortable errors: a Jesus who is merely a superlative man, and a God who stands aloof from matter and history. It also frames Christian hope realistically. The light shines in darkness, present tense; the darkness is real, and it is not victorious. The believer's confidence rests not on the world visibly brightening but on the light's demonstrated inextinguishability.",
      sensusPlenior: "When Genesis repeatedly says that God spoke and it was so, its human author gives no sign of conceiving that speech as a distinct divine person. Yet the canon presses a fuller sense. The psalmist already gathers all creation under a single phrase, the word of the LORD by which the heavens were made (Psalms 33:6), and the New Testament discloses that God has spoken finally in a Son, through whom he made the worlds (Hebrews 1:2) — the same Word who, John shortly declares, was 'made flesh' (John 1:14). Read whole, Scripture's first chapter carries a meaning its writer delivered but did not exhaust: the speech of God was never impersonal. This is not free association but the Bible's own retrospective reading of itself.",
    },
  },
  {
    templateId: "exegetical",
    reference: "Philippians 2:5-8",
    title: "The Downward Mind",
    sections: {
      passage: "Let this mind be in you, which was also in Christ Jesus: Who, being in the form of God, thought it not robbery to be equal with God: But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men: And being found in fashion as a man, he humbled himself, and became obedient unto death, even the death of the cross. (Philippians 2:5-8)\n\nThe passage arrives not as a freestanding treatise on Christ's person but as the engine of a pastoral appeal. Paul has just pleaded for unity of mind and for each member to esteem others better than themselves (Philippians 2:1-4); the command to let Christ's mind be in the congregation harnesses the deepest Christology in his letters to the ordinary friction of church life. What follows traces an unbroken descent from divine glory through servanthood and genuine humanity down to obedient death — with crucifixion named last, as the lowest step of all. The grammar of the whole runs downhill, and it runs downhill on purpose.",
      context: "Philippians is among the letters whose Pauline authorship is essentially undisputed. Paul writes from imprisonment — Rome, Ephesus, and Caesarea have each been argued, and the question remains open — to a church in a proud Roman colony he had founded on his second journey. Since the early twentieth century many scholars have proposed that verses 6 through 11 preserve a pre-Pauline hymn or confession, pointing to the passage's rhythmic structure and rare vocabulary; others reply that Paul was capable of elevated prose of his own and note that the hymn's reconstruction differs with every scholar who attempts it. The hypothesis is best held as a live scholarly proposal rather than a settled result. Either way, Paul deploys the material as fully his own.",
      observations: "Two parallel phrases carry the weight: the form of God and the form of a servant, the same noun binding what Christ was to what he chose to become. The clause the King James renders 'thought it not robbery to be equal with God' turns on a rare Greek noun whose sense is disputed: many recent interpreters take it to mean that Christ did not treat equality with God as a thing to exploit for his own advantage. Either reading agrees the equality was real. The pivotal verb, ekenosen, 'he emptied himself,' is defined not by any named subtraction but by the participles that follow: taking, being made, humbling. The emptying was an adding of servanthood, and the obedience descends step by step to the cross.",
      theology: "Canonically the descent is inseparable from its sequel: God highly exalts the obedient one and bestows the name above every name, so that every knee bows and every tongue confesses (Philippians 2:9-11). Behind that sequel stands one of the Old Testament's fiercest monotheistic oaths, in which the LORD swears that to him alone every knee shall bow and every tongue shall swear (Isaiah 45:23). Paul sets Jesus inside that oath without qualification, which tells the reader how much weight the form of God must bear. Many scholars also hear Isaiah's Servant behind the sequence of humiliation and subsequent exaltation (Isaiah 52:13), an echo that is likely though not explicit. Paul compresses the same movement elsewhere: though rich, for our sakes he became poor (2 Corinthians 8:9).",
      significance: "The passage refuses to let Christology remain a spectator sport. Paul does not say admire this mind; he says have it — among yourselves, in the way a congregation handles status, grievance, and preference. Christian humility, on this showing, is not low self-esteem but the deliberate downward use of real advantage for the good of others, since the one who possessed the highest conceivable advantage used it exactly that way. The passage also steadies sufferers: the road Christ walked ran through obedience and humiliation before exaltation, and the letter repeatedly casts the Philippians' own conflicts in that shape. A church formed by these verses measures greatness by what its strongest members are willing to lay down.",
    },
  },
];

export const STUDY_LIBRARY = ENTRIES.map((entry) => {
  const template = STUDY_TEMPLATES.find((t) => t.id === entry.templateId);
  return {
    templateId: entry.templateId,
    reference: entry.reference,
    title: entry.title,
    text: stringifyStudy(template, entry.sections),
  };
});
